spring:
  application:
    name: Journal App

  data:
    mongodb:
      uri : asd
      database : journaldb
      auto-indexing-creation : true

  main:
    allow-circular-references : true

server:
  port : 8081
  servlet :
    context-path : /journal
